"""empty message

Revision ID: 4b1059f127dd
Revises: d064aef74b2f
Create Date: 2024-04-27 16:19:59.695777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1059f127dd'
down_revision = 'd064aef74b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
